chanjo_report/server/blueprints/index/__init__.py
# -*- coding: utf-8 -*-
from .views import index_bp

chanjo_report/server/blueprints/index/views.py
# -*- coding: utf-8 -*-
import logging

from chanjo.store.models import Sample, Transcript
from flask import Blueprint, render_template

from chanjo_report.server.extensions import api

logger = logging.getLogger(__name__)
index_bp = Blueprint('index', __name__, template_folder='templates',
                     static_folder='static', static_url_path='/static/index')


@index_bp.route('/')
def index():
    sample_objs = api.query(Sample).limit(20)
    tx_models = api.query(Transcript).distinct(Transcript.gene_id).limit(20)
    return render_template('index/index.html', samples=sample_objs,
                           transcripts=tx_models)

chanjo_report/server/blueprints/index/templates/index/index.html
{% extends 'index/layouts/base.html' %}

{% block main %}
	<div class="container">
		<h3>Samples</h3>

		<ul class="list-group">
			{% for sample in samples %}
				<li class="list-group-item">
					<a href="{{ url_for('report.report', sample_id=sample.id) }}">
						{{ sample.name }}
					</a>
					({{ sample.id }})
				</li>
			{% endfor %}
		</ul>

		<h3>Genes</h3>
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					<th>Chromosome</th>
					<th>Gene</th>
				</tr>
			</thead>
			<tbody>
				{% for transcript in transcripts %}
					<tr>
						<td>{{ transcript.chromosome }}</td>
						<td>
							<a href="{{ url_for('report.gene', gene_id=transcript.gene_id) }}">
								{{ transcript.gene_name or transcript.gene_id }}
							</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

chanjo_report/server/blueprints/index/templates/index/layouts/base.html
<!DOCTYPE html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title>{% block title %}{% endblock %}</title>

	<meta name="description" content="Chanjo Report: coverage report generator">
	<meta name="author" content="Robin Andeer">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- place 'favicon.ico' + 'apple-touch-icon.png' in the root directory -->
	<link rel="Shortcut Icon"
				href="{{ url_for('static', filename='favicon.png') }}"
				type="image/x-icon">

	{% block css %}
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

		<!-- Optional theme -->
		<link rel="stylesheet" href="https://bootswatch.com/simplex/bootstrap.min.css">

		<!-- Customizations -->
		<link rel="stylesheet" type="text/css" href="{{ url_for('report.static', filename='main.css') }}">
	{% endblock %}

	{% block css_style %}{% endblock %}

	{% block js_top %}{% endblock %}
</head>
<body>
	{% block body %}
		<nav class="navbar navbar-default">
			<div class="container">
					<div class="navbar-header">
							<a class="navbar-brand" href="{{ url_for('index.index') }}">
								{% block header_title %}Chanjo Report{% endblock %}
							</a>
					</div>

					<ul class="nav navbar-nav">
						{% block nav %}{% endblock %}
					</ul>
			</div>
		</nav>

		{% block main %}{% endblock %}
	{% endblock %}

	{% block js_btm %}
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	{% endblock %}
</body>
</html>