chanjo_report/server/blueprints/report/__init__.py
# -*- coding: utf-8 -*-
from .views import report_bp

chanjo_report/server/blueprints/report/controllers.py
from chanjo.store.models import Sample
from flask import session

from chanjo_report.server.constants import LEVELS

from .utils import keymetrics_rows, samplesex_rows, transcripts_rows


def report_contents(request):
    """Check args or form provided by user request and prepare contents for report or pdf endpoints
    Args:
        request(flask.Request)

    Returns:
        data(dict)
    """

    sample_ids = request.form.getlist("sample_id") or request.args.getlist("sample_id")
    raw_gene_ids = request.form.get("gene_ids") or request.args.get("gene_ids")
    gene_ids = []
    if raw_gene_ids:
        gene_ids = [gene_id.strip() for gene_id in raw_gene_ids.split(",")]

    int_gene_ids = set()
    gene_id_errors = set()
    for gene_id in gene_ids:
        try:
            int_gene_ids.add(int(gene_id))
        except ValueError:
            gene_id_errors.add(gene_id)

    int_gene_ids = list(int_gene_ids)

    level = int(request.args.get("level") or request.form.get("level") or 10)
    extras = {
        "panel_name": (request.args.get("panel_name") or request.form.get("panel_name")),
        "level": level,
        "gene_ids": int_gene_ids,
        "show_genes": any([request.args.get("show_genes"), request.form.get("show_genes")]),
    }
    samples = Sample.query.filter(Sample.id.in_(sample_ids))
    case_name = request.form.get("case_name") or request.args.get("case_name")
    sex_rows = samplesex_rows(sample_ids)
    metrics_rows = keymetrics_rows(sample_ids, genes=int_gene_ids)
    tx_rows = transcripts_rows(sample_ids, genes=int_gene_ids, level=level)

    data = dict(
        sample_ids=sample_ids,
        samples=samples,
        case_name=case_name,
        sex_rows=sex_rows,
        levels=LEVELS,
        extras=extras,
        metrics_rows=metrics_rows,
        tx_rows=tx_rows,
        gene_id_errors=gene_id_errors,
    )
    return data

chanjo_report/server/blueprints/report/views.py
# -*- coding: utf-8 -*-
import datetime
import logging

from chanjo.store.models import Sample, Transcript, TranscriptStat
from flask import Blueprint, abort, jsonify, render_template, request, url_for
from flask_weasyprint import HTML, render_pdf

from chanjo_report.server.extensions import api

from . import controllers
from .utils import chromosome_coverage, keymetrics_rows, map_samples, transcript_coverage

logger = logging.getLogger(__name__)
report_bp = Blueprint(
    "report",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path="/static/report",
)


@report_bp.route("/genes/<gene_id>")
def gene(gene_id):
    """Display coverage information on a gene."""
    sample_ids = request.args.getlist("sample_id")
    sample_dict = map_samples(sample_ids=sample_ids)
    matching_tx = Transcript.filter_by(gene_id=gene_id).first()
    if matching_tx is None:
        return abort(404, "gene not found: {}".format(gene_id))
    gene_name = matching_tx.gene_name
    tx_groups = transcript_coverage(api, gene_id, *sample_ids)
    link = request.args.get("link")
    return render_template(
        "report/gene.html",
        gene_id=gene_id,
        gene_name=gene_name,
        link=link,
        tx_groups=tx_groups,
        samples=sample_dict,
    )


@report_bp.route("/genes", methods=["GET", "POST"])
def genes():
    """Display an overview of genes that are (un)completely covered."""
    skip = int(request.args.get("skip", 0))
    limit = int(request.args.get("limit", 30))
    exonlink = request.args.get("exonlink")
    sample_ids = request.args.getlist("sample_id")
    samples_q = Sample.filter(Sample.id.in_(sample_ids))
    level = request.args.get("level", 10)
    raw_gene_ids = request.args.get("gene_id") or request.form.get("gene_ids")
    completeness_col = getattr(TranscriptStat, "completeness_{}".format(level))
    query = (
        api.query(TranscriptStat)
        .join(TranscriptStat.transcript)
        .filter(completeness_col < 100)
        .order_by(completeness_col)
    )

    gene_ids = raw_gene_ids.split(",") if raw_gene_ids else []
    if raw_gene_ids:
        query = query.filter(Transcript.gene_id.in_(gene_ids))
    if sample_ids:
        query = query.filter(TranscriptStat.sample_id.in_(sample_ids))

    incomplete_left = query.offset(skip).limit(limit)
    total = query.count()
    has_next = total > skip + limit
    return render_template(
        "report/genes.html",
        incomplete=incomplete_left,
        level=level,
        skip=skip,
        limit=limit,
        has_next=has_next,
        gene_ids=gene_ids,
        exonlink=exonlink,
        samples=samples_q,
        sample_ids=sample_ids,
    )


@report_bp.route("/json_chrom_coverage", methods=["POST"])
def json_chrom_coverage():
    """Calculate mean coverage over all gene transcripts of a chromosome for one or more samples and return results as json"""

    results = {}
    data = request.json

    if not (data.get("chrom") and data.get("sample_ids")):
        return jsonify(results)

    chrom = str(data.get("chrom"))
    sample_ids = data.get("sample_ids").split(",")

    metrics_rows = chromosome_coverage(sample_ids, chrom).all()
    for row in metrics_rows:
        ts = row[0]  # An object of class TranscriptStat
        results[ts.sample_id] = row[1]  # Collect mean coverage over the chromosome transcripts

    return jsonify(results)


@report_bp.route("/json_gene_coverage", methods=["POST"])
def json_gene_coverage():
    """Calculate mean coverage over a list of genes for one or more samples and return results as json"""
    results = {}
    data = request.json

    if not (data.get("gene_ids") and data.get("sample_ids")):
        return jsonify(results)

    gene_ids = data.get("gene_ids").split(",")
    sample_ids = data.get("sample_ids").split(",")

    metrics_rows = keymetrics_rows(sample_ids, genes=gene_ids).all()

    for row in metrics_rows:
        ts = row[0]  # An object of class TranscriptStat
        results[ts.sample_id] = row[1]  # Collect mean coverage over the genes
    return jsonify(results)


@report_bp.route("/report", methods=["POST", "GET"])
def report():
    """Generate a coverage report for a group of samples."""
    data = controllers.report_contents(request)
    return render_template("report/report.html", **data)


@report_bp.route("/report/pdf", methods=["POST", "GET"])
def pdf():
    """Generate a PDF coverage report for a group of samples."""
    data = controllers.report_contents(request)

    html_report = render_template("report/report.html", **data)
    response = render_pdf(HTML(string=html_report))

    # check if the request is to download the file right away
    data_dict = request.form if request.method == "POST" else request.args
    if "dl" in data_dict:
        date_str = str(datetime.datetime.now().strftime("%Y-%m-%d"))
        fname = "_".join(["coverage-report", date_str + ".pdf"])

        if "case_name" in data_dict:  # if downloaded pdf should be named after a case sisplay name
            fname = "_".join([str(data_dict["case_name"]), fname])

        header = "attachment; filename={}".format(fname)
        response.headers["Content-Disposition"] = header

    return response

chanjo_report/server/blueprints/report/templates/index.html
{% extends 'layouts/base.html' %}

{% block body %}

  <div class="layout">

    <nav class="menu-bar">Chanjo Report</nav>

    <div class="layout__main content list__wrapper">
      
      <div class="list">

        <div class="list__container">
          <div class="list__header">
            <div>{{ _('Sample') }}</div>
            <div>{{ _('Group') }}</div>
          </div>

          <div class="list__section">
            {% for sample in samples %}
              <div class="list__item">
                <a href="{{ url_for('report.samples', filter_id=sample.id) }}">
                  {{ sample.id }}
                </a>

                <a href="{{ url_for('report.groups', filter_id=sample.group_id) }}">
                  {{ sample.group_id }}
                </a>
              </div>
            {% endfor %}
          </div>
        </div>

      </div>

    </div>

  </div>
  
{% endblock %}

chanjo_report/server/blueprints/report/templates/report.html
{% extends 'layouts/base.html' %}

{% block body %}
  <div class="layout">

    <nav class="menu-bar">
      <div>Chanjo Report</div>

      <a href="{{ url_for('report.index') }}">{{ _('Home') }}</a>
    </nav>

    <div class="layout__main content">

      <header>
        <h1>{{ _('Quality report clinical exome sequencing') }}</h1>
      </header>

      <section id="samples">
        <table class="table">
          <thead>
            <tr>
              <th>{{ _('Sample') }}</th>
              <th>{{ _('Group') }}</th>
              <th>{{ _('Cutoff') }} [x]</th>
            </tr>
          </thead>

          <tbody>
            {% for sample in samples %}
              <tr>
                <td>{{ sample.id }}</td>
                <td>{{ sample.group_id }}</td>
                <td class="right-align">{{ sample.cutoff }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </section>

      <section id="key-metrics">
        <h2 class="component__title">
          {{ _('Generally important metrics') }}
          {% if config.CHANJO_PANEL %}
            {{ _('for') }} {{ config.CHANJO_PANEL_CAPTION }}
          {% endif %}
        </h2>

        <table class="table">

          <thead>
            <tr>
              <th>{{ _('Sample') }}</th>
              <th>{{ _('Average coverage') }} [x]</th>
              <th>{{ _('Average completeness') }} [%]</th>
            </tr>
          </thead>

          <tbody>
            {% for sample_id, _, coverage, completeness in key_metrics %}
              <tr>
                <td>{{ sample_id }}</td>
                <td class="right-align">
                  {{ coverage|round(3) }}
                </td>
                <td class="right-align">
                  {{ (completeness * 100)|round(3) }}
                </td>
              </tr>
            {% endfor %}
          </tbody>

        </table>
      </section>

      <section id="diagnostic-yield">
        <h2 class="component__title">
          {{ _('Diagnostic yield') }}
          {% if config.CHANJO_PANEL %}
            {{ _('for') }} {{ config.CHANJO_PANEL_CAPTION }}
          {% endif %}
        </h2>

        <table class="table">

          <thead>
            <tr>
              <th>{{ _('Sample') }}</th>
              <th>{{ _('Diagnostic yield') }} [%]</th>
            </tr>
          </thead>

          <tbody>
            {% for sample_id, _, value in diagnostic_yield %}
              <tr>
                <td>{{ sample_id }}</td>
                <td class="right-align">
                  {{ (value * 100)|round(3) }}
                </td>
              </tr>
            {% endfor %}
          </tbody>

        </table>
      </section>

      <section id="gender">
        <h2 class="component__title">{{ _('Gender confirmation') }}</h2>

        <table class="table">

          <thead>
            <tr>
              <th rowspan="2">{{ _('Sample') }}</th>
              <th rowspan="2">{{ _('Gender') }}</th>
              <th colspan="2" class="center-align">
                {{ _('Average coverage') }} [x]
              </th>
            </tr>
            <tr>
              <th class="th-secondary">{{ _('Chromosome') }} X</th>
              <th class="th-secondary">{{ _('Chromosome') }} Y</th>
            </tr>
          </thead>

          <tbody>
            {% for sample_id, gender, x_coverage, y_coverage in genders %}
              <tr>
                <td>{{ sample_id }}</td>
                <td>{{ _(gender) }}</td>
                <td class="right-align">{{ x_coverage|round(3) }}</td>
                <td class="right-align">{{ y_coverage|round(3) }}</td>
              </tr>
            {% endfor %}
          </tbody>

        </table>        
      </section>

      <section id="thesaurus" class="break-here">

        <h2>{{ _('Explanations') }}</h2>
        
        <div class="explanation">
          <h3 class="explanation__title">{{ _('General') }}</h3>

          <p>
            {{ _('The parts of the genome that has been analyzsed') }}
            {{ _('is composed of all protein coding, exonic intervals') }}
            {{ _('referenced in the') }}
            <a href="http://www.ncbi.nlm.nih.gov/CCDS/CcdsBrowse.cgi">
              {{ _('CCDS database') }}
            </a>.
            {{ _('Additionally, the data also includes spicing sites') }}
            ({{ _('donator and acceptor positions') }},
            {{ _('two bases on either of each exon') }}.)
          </p>

          <p>
            <strong>{{ _('Coverage') }}</strong>:
            {{ _('An alternative measure of sequence depth') }}.
            {{ _('It is defined as the ratio of bases') }}
            {{ _('sequenced deeper than a specified cutoff') }},
            {{ _('e.g. 10x') }}.
            {{ _('The current cutoff is defined per sample') }}
            {{ _('and is found i the "Cutoff" column (first table)') }}.
          </p>

          <p>
            <strong>{{ _('Completeness') }}</strong>:
            {{ _('gives an overview of the success of sequencing') }}.
            {{ _("It's defined as the ratio of transcripts") }}
            {{ _('with a completeness of') }}100%.
          </p>
        </div>


        {% if config.CHANJO_PANEL %}
          <div class="explanation">
            <h3 class="explanation__title">
              {{ _('Generally important metrics') }}
              {{ _('for') }}
              {{ config.CHANJO_PANEL_CAPTION }}
            </h3>

            <p>
              {{ _('The measure of coverage was genereated through matching of gene IDs from') }}
              <code>{{ config.CHANJO_PANEL_CAPTION }}</code>.
              {{ _('Note that estimations were made regarding coverage and completeness') }}
              {{ _('on the level of transcripts') }}.
            </p>
          </div>
        {% endif %}

      </section>

    </div>

  </div>

{% endblock %}

chanjo_report/server/blueprints/report/templates/report/genes.html
{% extends 'report/layouts/base.html' %}

{% block js_btm %}
	{{ super() }}

	<script src="//cdnjs.cloudflare.com/ajax/libs/highcharts/4.2.3/highcharts.js"></script>
{% endblock %}

{% block main %}
<div class="container">

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4>Incomplete transcripts</h4>
				</div>
				<ul class="list-group">
					<li class="list-group-item">
						Samples:
						{% for sample in samples %}
							<strong>{{ sample.name or sample.id }}</strong>
						{% endfor %}
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<ul class="nav nav-pills">
				{% for level_id, _ in levels.items() %}
					<li {% if level_id == level|int %}class="active"{% endif %}>
						<a href="{{ url_for('report.genes', level=level_id, gene_id=gene_ids|join(','), sample_id=sample_ids) }}">
							Completeness {{ level_id }}x
						</a>
					</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<br>

	<div class="row">
		<div class="col-md-12">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>Gene</th>
						<th>Transcript</th>
						<th>Sample</th>
						<th>Completeness {{ level }}x [%]</th>
					</tr>
				</thead>
				<tbody>
					{% for stat in incomplete %}
						<tr>
							<td>
								<a href="{{ url_for('report.gene', gene_id=stat.transcript.gene_id, link=exonlink, sample_id=sample_ids) }}">
									{{ stat.transcript.gene_name or stat.transcript.gene_id }}
								</a>
							</td>
							<td>{{ stat.transcript_id }}</td>
							<td>{{ stat.sample.name }}</td>
							<td class="text-right">
								{{ stat|attr("completeness_%s"|format(level))|round(2) }}
							</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="4">No transcripts found or level not annotated.</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6">
			{% if skip > 0 %}
				{% set next_skip = 0 if (skip - limit) < 0 else (skip - limit) %}
				<form id="report-genes-previous" method="POST" action="{{ url_for('report.genes', level=level, skip=next_skip, limit=limit, sample_id=sample_ids) }}">
					<input type="hidden" name="gene_id" value="{{ gene_ids|join(',') }}">
					<button type="submit" class="btn btn-default">Previous</button>
				</form>
			{% endif %}
		</div>
		<div class="col-md-6">
			{% if has_next %}
				<div class="float-right">
					<form id="report-genes-next" method="POST" action="{{ url_for('report.genes', level=level, skip=(skip + limit), limit=limit, sample_id=sample_ids) }}">
						<input type="hidden" name="gene_id" value="{{ gene_ids|join(',') }}">
						<button type="submit" class="btn btn-default">Next</button>
					</form>
				</div>
			{% endif %}
		</div>
	</div>
</div>

{% endblock %}

chanjo_report/server/blueprints/report/templates/report/index.html
{% extends 'report/layouts/base.html' %}

{% block main %}
	<div class="container">
		<h3>Samples</h3>
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					<th>{{ _('Sample') }}</th>
					<th>{{ _('Group') }}</th>
				</tr>
			</thead>
			<tbody>
				{% for sample in samples %}
					<tr>
						<td><a href="{{ url_for('report.group', sample_id=[sample.sample_id]) }}">{{ sample.sample_id }}</a></td>
						<td>
							<a href="{{ url_for('report.group', group_id=sample.group_id) }}">
								{{ sample.group_id }}
							</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

		<h3>Genes</h3>
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					<th>Chromosome</th>
					<th>Gene</th>
				</tr>
			</thead>
			<tbody>
				{% for gene in genes %}
					<tr>
						<td>{{ gene.chromosome or '-' }}</td>
						<td>
							<a href="{{ url_for('report.gene', gene_id=gene.gene_id) }}">
								{{ gene.gene_id }}
							</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

chanjo_report/server/blueprints/report/templates/report/report.html
{% extends 'report/layouts/base.html' %}

{% block nav %}
	<li>
		{{ filters_form(sample_ids, extras, pdf=True, hidden=True) }}
	</li>
{% endblock %}

{% block main %}
	<div class="container">
		<div class="panel-group hidden-print" id="filter-accordion">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
						<a role="button" data-toggle="collapse" data-parent="#accordion" href="#view-filters">Customize</a>
					</h4>
				</div>

				<div id="view-filters" class="panel-collapse collapse">
					<div class="panel-body">
						{{ filters_form(sample_ids, extras) }}
					</div>
				</div>
			</div>
		</div>

		{% if gene_id_errors %}
			<span style="background-color:#d9534f;color:white;">Gene list should contain comma-separated HGNC numerical identifiers, not strings. Unsupported gene identifiers: {{gene_id_errors}} were not taken into account.</span>
		{% endif %}

		<h2>{{ _('Quality report') }}: {{ _('clinical sequencing') }}</h2>
		{% if extras.panel_name %}
			<p>{{ _('Based on gene panel') }}: <strong>{{ extras.panel_name }}</strong></p>
		{% endif %}
		{{ overview_table(sex_rows) }}

		<h3>{{ _('Generally important metrics') }}</h3>
		{{ metrics_table(metrics_rows) }}

		<h3>{{ _('Transcript coverage') }} {{ _('at') }}: {{ extras.level }}x</h3>
		{{ transcripts_table(tx_rows) }}

		<h3>{{ _('Explanations') }}</h3>
		{{ explanations(extras.level) }}

		<hr>
		<div class="text-center">{{ _('End of report') }}</div>
	</div>
{% endblock %}

{% macro overview_table(sex_rows) %}
	<div class="table-responsive">
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					<th rowspan="2">{{ _('Sample') }}</th>
					<th rowspan="2">{{ _('Group') }}</th>
					<th rowspan="2">{{ _('Analyzed at') }}</th>
					<th rowspan="2">
						{{ _('Sex') }}
						{{ _('according to sequence data') }}
					</th>
					<th colspan="2" class="center-align">
						{{ _('Average coverage') }} [x]
					</th>
				</tr>
				<tr>
					<th class="th-secondary">{{ _('Chromosome') }} X</th>
					<th class="th-secondary">{{ _('Chromosome') }} Y</th>
				</tr>
			</thead>
			<tbody>
				{% for sample in sex_rows %}
					<tr>
						<td>{{ sample.sample }}</td>
						<td>{{ sample.group }}</td>
						<td>{{ sample.analysis_date.date() }}</td>
						<td>{{ _(sample.sex) }}</td>
						<td class="text-right">{{ sample.x_coverage|round(3) }}</td>
						<td class="text-right">{{ sample.y_coverage|round(3) }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endmacro %}

{% macro metrics_table(metrics_rows) %}
	<div class="table-responsive">
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					<th>{{ _('Sample') }}</th>
					<th>{{ _('Average coverage') }} [x]</th>
					{% for level_int, level_key in levels.items() %}
						<th>{{ _('Completeness') }} {{ level_int }}x [%]</th>
					{% endfor %}
				</tr>
			</thead>
			<tbody>
				{% for data in metrics_rows %}
					<tr>
						<td>{{ data.TranscriptStat.sample.name or data.TranscriptStat.sample.id }}</td>
						<td class="text-right">{{ data.mean_coverage|round(2) }}</td>
						{% for level_int, level_key in levels.items() %}
							<td class="text-right">{{ data|attr(level_key)|round(2) if data|attr(level_key) }}</td>
						{% endfor %}
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endmacro %}

{% macro transcripts_table(transcript_rows) %}
	<table class="table table-bordered table-hover">
		<thead>
			<tr>
				<th>{{ _('Sample') }}</th>
				<th>{{ _('Fully covered transcripts') }} [%]</th>
				<th>{{ _('Incompletely covered') }} {{ _('transcripts') }}</th>
				{% if extras.show_genes %}
					<th>{{ _('Incompletely covered') }} {{ _('genes') }} (max 50)</th>
				{% endif %}
			</tr>
		</thead>
		<tbody>
			{% for data in transcript_rows %}
				<tr>
					<td>{{ data.sample.name or data.sample.id }}</td>
					<td class="text-right">{{ data.yield|round(3) }}</td>
					<td class="text-center">
						{{ data.missed_count }} / <small>{{ data.total }}</small>
					</td>
					{% if extras.show_genes %}
						<td><small>
							{% for tx_stat in data.missed.limit(50) %}
								{{ tx_stat.transcript.gene_name or tx_stat.transcript.gene_id }}
							{% else %}
								-
							{% endfor %}
						</small></td>
					{% endif %}
				</tr>
			{% else %}
				<tr>
					<td colspan="{{ 4 if extras.show_genes else 3 }}">
						Inga ofullständigt täckta transkript.
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endmacro %}

{% macro explanations(cutoff) %}
	<h4>{{ _('General') }}</h4>
	<p>
		<a href="http://lomereiter.github.io/sambamba/" title="Sambamba">Sambamba</a>
		{{ _('is used for coverage analysis based on read alignment.') }}
		{{ _('Duplicates, reads with mapping quality less than 10 as well as bases with a base quality less than 10 are not included in the analysis.') }}
		{{ _('Bases that overlap between read pairs are only counted once.') }}

		{{ _('The parts of the genome that has been analyzed') }}
		{{ _('is composed of all protein coding, exonic intervals defined in') }}
		<a href="http://www.genenames.org/">HGNC</a>.

		{% if includes_splice_sites %}
			{{ _('Additionally, the data also includes spicing sites') }}
			({{ _('donator and acceptor positions') }},
			{{ splice_site_interval }}
			{{ _('bases on either of each exon') }}).
		{% endif %}
	</p>

	{% if config.CHANJO_PANEL %}
		<p>
			{{ _('Final coverage metrics were calculated for genes from the clinical panels') }}:
			<code>{{ config.CHANJO_PANEL_NAME }}</code>.
			{{ _('Note that estimations were made regarding coverage and completeness') }}
			{{ _('on the level of transcripts') }}.
		</p>
	{% endif %}

	<p>
		<strong>{{ _('Completeness') }}</strong>:
		{{ _('defined as the ratio of bases') }}
		{{ _('sequenced deeper than a specified cutoff') }},
		{{ _('e.g. 10x') }}.
	</p>

	<p>
		<strong>{{ _('Transcript coverage') }}</strong>:
		{{ _('defined as the ratio of transcripts that are fully covered') }},
		{{ _('i.e. with a completeness of') }} 100% {{ _('at') }} {{ cutoff }}x.
	</p>

	<p>
		<strong>{{ _('Gender prediction from data') }}</strong>:
		{{ _('calculated by comparing relative chromosome coverage') }}
		(X/Y).
		{{ _('Some reads randomly map to the Y chromosome') }}.
		{{ _('Therefore, a less than 10 fold difference is used to infer a "male" sample') }}.
	</p>
{% endmacro %}

{% macro filters_form(sample_ids, extras, pdf=False, hidden=False) %}
	<form method="POST"
		  action="{{ url_for('report.pdf' if pdf else 'report.report') }}">
		<div class="{% if hidden %}navbar-form{% endif %}">
			<div class="form-group">
				<div class="row" {% if hidden %}hidden{% endif %}>
					<div class="col-xs-6">
						<label class="control-label">Completeness cutoff</label>
						<select class="form-control" name="level">
							{% for level, _ in levels.items() %}
								<option value="{{ level }}" {% if level == extras.level %} selected {% endif %}>{{ level }}x</option>
							{% endfor %}
						</select>
					</div>

					<div class="col-xs-6">
						<label class="control-label">Gene panel name to <i>display</i></label>
						<input class="form-control" name="panel_name" type="text" placeholder="Skeletal dysplasia 3.2" value="{{ extras.panel_name or '' }}">
					</div>
				</div>
			</div>

			<div class="form-group">
				<div class="row" {% if hidden %}hidden{% endif %}>
					<div class="col-xs-7">
						<label class="control-label">Included genes</label>
						<div><input class="form-control" type="text" name="gene_ids" value="{{ extras.gene_ids|join(', ') }}" placeholder="ADK,GIT"></div>
					</div>

					<div class="col-xs-3">
						<label class="control-label">Show genes</label>
						<div><input type="checkbox" name="show_genes" {% if extras.show_genes %}checked{% endif %}></div>
					</div>

					<div class="col-xs-2">
						<label class="control-label">&nbsp;</label>
						<button class="btn btn-default form-control" type="submit">Update</button>
					</div>
				</div>
			</div>

			{% for sample_id in sample_ids %}
				<input type="text" name="sample_id" value="{{ sample_id }}" hidden>
			{% endfor %}

			{% if hidden %}
				<button class="btn btn-link navbar-btn" type="submit">PDF</button>
			{% endif %}
		</div>
	</form>
{% endmacro %}